### ISSUE TITLE
special.vals dont work at all

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/phng#18]
x = ParamReal$new("x", lower = 1, special.vals = list("a"))

that does not even create an object.
 
- the "test" function must be  unit tested
- it needs to be documented what the effect on "sample" is.
- it needs to be documented what the effect on "denorm" is

**Comment by jakob-r** [comment]
creation works now but on the rest I agree

**Comment by berndbischl** [comment]
> creation works now but on the rest I agree

can you please add at least SOME tests if you do that?

**Comment by jakob-r** [comment]
Is tested now
