### ISSUE TITLE
add unit tests to make sure that an empty param set can be created and operations on it make sense

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/phng#19]

**Comment by jakob-r** [comment]
Why do we need an empty ParamSet?

**Comment by berndbischl** [comment]
why do you need an empty list? or an empty vector?

**Comment by berndbischl** [comment]
the simple answer is because a learner can have 0 params. now what do you put in the slot of the param set? and empty param set

**Comment by jakob-r** [comment]
If a ParamSet does not need to have any Params why does a learner have to have a ParamSet?

**Comment by berndbischl** [comment]
huh? every mlr learner has a param.set slot. now what do you pass in there?

**Comment by jakob-r** [comment]
is covered by the new tests
