### ISSUE TITLE
ParamSetFlat operation API seems inconsistent

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/phng#22]
apparently i can ask about bounds of all params in the set, so these thinks are there:
- lower, upper, range

but i cannot ask about nlevels or values.

**Comment by berndbischl** [comment]
one improvement is to make range a list col, that either includes 
c(low, upper) or (T,F) or the charvec of discrete values

**Comment by jakob-r** [comment]
for lower and upper i always expect a number. everything else is weird. 
we do not need to have this helper active binding for stuff we do not need. Nobody stops you from applying over all params with whatever request you have.

**Comment by berndbischl** [comment]
you havent adressed anything i wrote in this issue?

**Comment by berndbischl** [comment]
and i havent even suggested to add an AB?

**Comment by berndbischl** [comment]
what i wrote that the interface is inconsistent. you are inducing some operation from some params to the PS. and some you dont. following your argument, lower and upper should be removed as AB from the PS. as you said: one can easily map over the PS right ...? 
(yeah, sorry, invalid argument here, too)

**Comment by jakob-r** [comment]
I added all the mentioned fields. For further precise requests please open a new PR
