### ISSUE TITLE
Check public methods of ParamSetTree

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/phng#33]
Do we need the following to be public?

* setRootHandle (it is not even used anywhere)
* asample
* asample.render2str (completely remove that)
* getFlatList - i like the option to get a nested list, but this should then be `sampleList` and directly sample. Or is ist exactly what `getRecursiveList()` does?

**Comment by smilesun** [comment]
I just checked, it it not possible currently to set asample to be private since asample need to call asample from another paramsetTree.

**Comment by smilesun** [comment]
asample.render2str  and setRootHandle has been removed

**Comment by smilesun** [comment]
getFlatList and getRecursiveList() has been wrapped by sampleList()

**Comment by smilesun** [comment]
getRecursiveList() and getFlatlist() can not be set to private since they need to call other objects same name method

**Comment by smilesun** [comment]
@jakob-r , how do you think of the solution at branch tree2?  I have put the funtionalities in 2 classes. ParamSetTree and ParamSetTreeX where in the latter I put functions you do not like and we do not expose them to the user?

**Comment by smilesun** [comment]
@jakob-r , see latest commit Latest commit 143a2c4
