### ISSUE TITLE
export functions

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/phng#34]
Some functions are not exported although they seem to be needed
e.g.
`ParamTreeFac`

@smilesun Please check that the vignettes run with an installed version of phng.

**Comment by smilesun** [comment]
@jakob-r , we do not need to export ParamTreeFac since it is only used internally. the vignett compiles on my machine in a clean R session with phng installed.  Did you use the tree branch installed on your computer ?

**Comment by jakob-r** [comment]
my bad. sorry
