### ISSUE TITLE
Why do Paramset and ParamSimple BOTH inherit from ParamNode?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/phng#4]
many properties of ParamNode do not make sense for ParamSets? like storage.type, tags, etc?

(transfered from @berndbischl FIXME)

**Comment by jakob-r** [comment]
When we want to combine different paramsets, they are also nodes. Also I want to store the parameter values of a ParamSet somehow. This I would do in a list. Therefore the storage.type.
Also it does not hurt to have tags.

Can you specify the etc. slots?

**Comment by berndbischl** [comment]
lets wait for #12 to be resolved
